### ISSUE TITLE
How to handle deleted job

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#109]
When the job is in `deleted` state, the raw data, `stats` are still available.
At the moment, the library assumes `deleted` jobs are bad inputs so one will see an error such as `'2/2/1' does not have any items` or `2/2/1 has 'deleted' state`.

It's possibly to run rules against such jobs, but does it make any sense?

**Comment by Alexandr1988** [comment]
I don't think we need to run Arche through the deleted jobs. If the necessary job was deleted then we have to find an other one to work with

**Comment by manycoding** [comment]
Deleted job is a bad job.
