### ISSUE TITLE
value_counts is slow for nested columns

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#115]
More data to follow
Because `value_counts` is slow, any big df makes report_all awfully slow.

1. See if it can be improved
2. If not, exlude get_categories from report_all
or make a parameter like (fast=True)

**Comment by manycoding** [comment]
Introduced in #100

**Comment by manycoding** [comment]
The slowest are object columns, specifically nested data. The difference in 10-1000x.
@ejulio @Alexandr1988, I am thinking about alternatives:
1. Ignore object columns
2. Fast argument, so category won't use object columns, and fast schema #5 `Arche(..fast=True)`. Default False.
3. Leave as it is (users are expected to use specific rules)
4. Use flat_df - very fast, but the categories pictures in this case is not the same since data is flattened.

**Comment by victor-torres** [comment]
If there's not a cache, seems like you're calculating `value_counts` twice.
See: https://github.com/scrapinghub/arche/pull/100/files#r295002793

**Comment by victor-torres** [comment]
You could use a generator to reduce the number of calls to the function. 
See: https://github.com/scrapinghub/arche/pull/100/files#r295004052

**Comment by manycoding** [comment]
@victor-torres It doesn't make any difference since object are that slow anyway.
But I compared performance
![Screenshot 2019-06-18 at 16 35 41](https://user-images.githubusercontent.com/10396557/59718009-2c680c00-91e7-11e9-96e0-a29f3b0395e9.png)

**Comment by ejulio** [comment]
No major comments here.
Maybe I can search a bit on pandas internals.
I'd only mention that we would need to be careful about `fast` argument because we already use something like that for `fastjsonschema` and we need to avoid misinterpretations :)

**Comment by manycoding** [comment]
>I'd only mention that we would need to be careful about fast argument 
I thought we can put `fast` and if it's True use the fastest validations
1. excluding nested data from categories (by using common with `flat_df` columns, I think that's the fastest way)
2. fastjsonschema instead of jsonschema

But we need to find a solution since right now `value_counts` degrades performance in 100-1000x times if nested columns are there. Which makes this particular dataset untestable.

Without nested data it takes around a couple of minutes.
Full dataset - I stopped after 30 minutes.
