### ISSUE TITLE
Neat report

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#119]
- [x] Markdown printer to make everything consistent - those ugly fonts
![Screenshot 2019-06-19 at 13 47 00](https://user-images.githubusercontent.com/10396557/59788019-c2a83a80-9298-11e9-800c-ef055603f364.png)
- [ ] Consistent rules output - SKIPPED\PASSED\OK, then details. Probably move all details to the detailed part, as in result.show().
- [x] Not found tags - skipped
- [x] Job errors - one link, make it clickable
- [x] In the detailed part, text first, then graphs

**Comment by manycoding** [comment]
@alexander-matsievsky

> @manycoding Somewhat unrelated to the PR at hand but what do you think about switching to Markdown for reporting, Valery?

I got back to this one. I would love to use markdown but it doesn't support coloring.

**Comment by alexander-matsievsky** [comment]
@manycoding You mean this?

![image](https://user-images.githubusercontent.com/3784691/60820529-47a4b680-a1aa-11e9-853a-886894eb8f1b.png)

Markdown allows HTML embedding.
