### ISSUE TITLE
Data download consumes too much memory

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#140]
Downloading 3m of items consumes about 8gb memory. Not much, but could it be lower?

Possible solution with chunks - https://github.com/scrapinghub/python-scrapinghub/issues/121

**Comment by manycoding** [comment]
1. Read raw data to numpy in chunks, using coroutines - `yield`. Then collate so the index stays in order.
2. Same with DataFrame.

We cannot go from max DataFrame size yet, but possibly its memory consumption is much lower than when it's being initialized.

**Comment by manycoding** [comment]
The raw data is stored in a numpy array and has certain size. When downloading, there's no memory overhead (the memory consumption is smaller then the result array).
Thus, I don't see any room for improvement as long as `raw` is kept (used for JSON schema validation)

Pandas looks more memory efficient.

Code https://jupyter.scrapinghub.com/user/v/lab/tree/shared/Arche/Memory%20consumption%20bench.ipynb
Bench notebook (to accuratelly measure memory consumption) https://jupyter.scrapinghub.com/user/v/lab/tree/shared/Arche/Memory%20consumption.ipynb

**Comment by manycoding** [comment]
@andersonberg @felipefin @alexandr1988 Have you hit the wall with memory recently, in particular in Kosmonaut high memory profile?
As I haven't found a way to optimize memory in the library, I can increase memory for our server if needed.

**Comment by FelipeFin** [comment]
I remember having issues downloading more than 500k items, however I was not using Kosmonaut.
I'll keep that in mind next time I face this kind of situations.

**Comment by Alexandr1988** [comment]
I think I didn't have a task like this. Will let you know if I have

**Comment by andersonberg** [comment]
No, I didn't use Kosmonaut with high memory yet. Adding to that, I didn't face any memory problems in  the Arche profile

**Comment by manycoding** [comment]
Closing because the most straightforward way is to up the server memory.
