### ISSUE TITLE
Anomalies - is Benford's law useful at all?

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#148]
https://github.com/milcent/benford_py/blob/master/Demo.ipynb

I'd like to check on real data, but so far I think:
1. This is only useful when the significant amount of numerical data is affected, since few wrong numbers (with certain variation) don’t affect the stats graph.
2. Therefore, if the bug is big, it’d be found earlier by other means.

Here's the notebook https://jupyter.scrapinghub.com/user/v/lab/tree/shared/Arche/benfords_law.ipynb

@ivankivanov @ejulio @alexander-matsievsky @tcurvelo @andersonberg @victor-torres

**Comment by ejulio** [comment]
I think these kids of checks are fine.
Specially if they don't exist in other libraries (scipy, numpy, ...).
However, I think we need to come with a good API to them so that they are not forgotten.
Also, not sure if they would be good if embedded in `anomalies` for example

**Comment by ejulio** [comment]
The benford's law sounds good, but not sure if in an API returning a True/False value.
Maybe it can be added as kind of comparison plot.
For example, `plot_benford_comparison()` and then the user can validate the result.

In terms of a True/False result, I'd suggest some kind of statistical test (permutation test for example).
https://rasbt.github.io/mlxtend/user_guide/evaluate/permutation_test/
https://thomasleeper.com/Rcourse/Tutorials/permutationtests.html
https://www.r-bloggers.com/what-is-a-permutation-test/

**Comment by manycoding** [comment]
>Maybe it can be added as kind of comparison plot.
For example, plot_benford_comparison() and then the user can validate the result.

Do you mean comparison between a job field and benford's numbers or between jobs fields?

**Comment by ejulio** [comment]
Between job field and benford's expected distribution.

**Comment by manycoding** [comment]
I didn't find it very useful.
