### ISSUE TITLE
Save graphs between sessions

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#45]
At the moment ipywidgets are not saved between sessions, meaning the output is lost once a notebook is closed. https://github.com/jupyterlab/jupyterlab/issues/5235

And using `plotly.offline.iplot()` duplicates any widgets, making the output polluted with copies of progress bars (which are widgets). https://github.com/jupyter-widgets/ipywidgets/issues/2359

**Comment by ivankivanov** [comment]
Do you have an example notebooks which I can use for tests?

Btw will it be OK if the widgets or plots are saved as jpg-s:

https://github.com/jupyter-widgets/ipywidgets/issues/1291

https://plot.ly/python/static-image-export/

**Comment by manycoding** [comment]
@ivankivanov Any notebook with graphs (except for DQR) will do - just make sure you use `master`.

Let me restate the problem again:
1. Plotly saves the graphs between sessions, but if duplicates widgets.
2. We need widgets at least for progress bar, but they are also good for printing graphs. If you print graphs as widgets, they are not saved between sessions.

I think saving graphs as png after the notebook closed is ok. But before we close we want to interact with them - it means JS, normal way, no `png`.
