### ISSUE TITLE
JupyterLab performance degrades with the number of plotly graphs

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#72]
It seems that in a notebook graphs are printed in a smaller size first, and then autosized to the page. This autosizing freezes the page for a second and looks like an issue.
Set the proper size by default?

**Comment by manycoding** [comment]
https://github.com/jupyterlab/jupyter-renderers/issues/171

**Comment by manycoding** [comment]
https://altair-viz.github.io/

**Comment by manycoding** [comment]
Current workaround - use classic Notebook UI.

**Comment by manycoding** [comment]
JupyterLab 1 can speed it up
Anyway, seaborn is worth considering.

**Comment by DraTeots** [comment]
Any updates on the issue?

**Comment by manycoding** [comment]
I just checked it at JL 1.1, seems much faster. So it works for now for our purposes.

**Comment by manycoding** [comment]
Fixed in #124

**Comment by DraTeots** [comment]
But performance still degrades...

**Comment by manycoding** [comment]
Yes, as with any other similar tool. For a typical usage for this library, the performance is good enough - for me, at least, it's not noticeable.

**Comment by DraTeots** [comment]
Actually it freezes for minutes. But probably, it is not an issue of this project.

**Comment by manycoding** [comment]
Then I suggest to leave package versions and how to reproduce it in jupyterlab/jupyter-renderers#171
