### ISSUE TITLE
Replace ' with "

### ISSUE THREAD

**Issue by Alexandr1988** [scrapinghub/arche#82]
basic_json_schema generates schemas with single quotes and then tox complains with an error: "E             Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"

**Comment by manycoding** [comment]
How the `tox` is connected with this? What are the steps to reproduce?
By default `basic_json_schema` returns a python dictionary which is meant to be used in the Jupyter.
To get a `json` representation, you can use `BasicSchema.json()` method https://arche.readthedocs.io/en/latest/nbs/Schema.html#Creating-schema
