### ISSUE TITLE
Consuming items data to df creates inconsistencies with jsonschema

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#83]
Caused by #75  

Pandas makes it's [own casts](https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#support-for-integer-na) which is incompatible with jsonschema dict validation by default.
For example if items data:
`[{"availability": 1, "_key": "0"}, {"_key": "1"}}]`
or
`[{"availability": 1, "_key": "0"}, {"availability": None, "_key": "1"}}]`
DataFrame in both cases would be
```
  _key  availability
0    0           1.0
1    1           NaN
```
Yet JSON Schema `null` type means `None`, and missing field is validated with not putting it in `required`. So we have:
Missing field (on purpose)
```
{
    "required": ["_key"],
    "properties": {
        "_key": {"type": "string"},
        "availability": {"type": "integer"},
    },
    "additionalProperties": False,
}
```
`None` field (on purpose)
```
{
    "required": ["_key", availability],
    "properties": {
        "_key": {"type": "string"},
        "availability": {"type": ["integer", null]},
    },
    "additionalProperties": False,
}
```

Last but not least, the inconsistencies between JSON schema and data persist when we feed a dataframe directly (unless a user manages it himself).

**Comment by manycoding** [comment]
I don't see any other choice as to store `dict` too.
To make df compatible with items data we need:
1. Make sure integers are not casted to floats in columns with `NAN`
2. Remove NAN for values which are not presented in items data (so we need to check with the dict anyway)

**Comment by manycoding** [comment]
Two ways:
1. NAN are missing values - read a first item as a dict, save info about integers\floats and cast the types appropriately. Keep only df
2. Keep raw data.

**Comment by manycoding** [comment]
this can help to save memory if df only approach is to stay https://github.com/scrapinghub/python-scrapinghub/issues/121

**Comment by victor-torres** [comment]
I believe the first thing to do is create a test case to expose the problem. 

Then, my first suggestion is to try to cast the Pandas' column right after its ingestion.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.astype.html

**Comment by manycoding** [comment]
@victor-torres The test case was indeed the first thing.
The type can probably be casted but:
1. there's no guarantee we find an item with all the fields, so we can easily miss one
2. casting slows down
Even having float\integers right doesn't solve `NAN` issue.
P.S. I update the description so it's more obvious.

**Comment by BurnzZ** [comment]
@manycoding I'm not familiar on how jsonschema validates fields with `null` values, but I found some problems that inconsistently validates `NaN` values in when reading items using https://github.com/scrapinghub/python-scrapinghub which are then placed into a `pd.DataFrame`.

Suppose we want to check the `null`-ness of a given column/field, as you have correctly mentioned, `pandas` casts it into a `NaN` value. So instinctively, we could do `np.isnan(df.some_field)` to check.

However, in some weird cases it would return the incorrect boolean value even when there are indeed `NaN` values in it.

I found it best to use `pd.isnull(df.some_field)` instead to consistently identify them correctly.

Perhaps if we could swap out jsonschema's validation right from Arche, this might solve the inconsistencies.

**Comment by ivankivanov** [comment]
Interesting article about pandas and handling missing data:

https://www.oreilly.com/learning/handling-missing-data

what if instead pandas data is loaded into numpy arrays. Something like:

```
def load_data(path):
    with open(path) as f:
        data = json.load(f)
    print(data)
    return np.asarray(data) 
```

in this way we will have:

- :one: empty string - `{"city": "Prague", "name": ""}`  - 'name': ''
- :two: missing field - `{"city": "Berlin"}` - nothing
- :three: `None` - `{"city": "Prague", "name": None}` - error because None is not valid json
- :four: `null` - `{"city": "Prague", "name": null}` - 'name': None
 
And on the other hand we have from one side:
-  the pythonic way for storing missing values - None
- json representation for missing values - null

**Comment by manycoding** [comment]
> Perhaps if we could swap out jsonschema's validation right from Arche, this might solve the inconsistencies.
Not right now, since it's a useful tool which cannot be easily replaced. Removing jsonschema would mean everybody will have to use pandas to check fields types and regex manually or such validation (meaning read schema and validate `df`) will have to be created for pandas to replace jsonschema library.

**Comment by manycoding** [comment]
>what if instead pandas data is loaded into numpy arrays. Something like:
This one is good.

One note about json null None - from jsonschema validation point of view, we don't care about json file. It just works.
What we care about is that if we have a missing field in items data - it will be missing in the data `jsonschema` verifies. And if the field is `None`, we care that it is `None` in the data `jsonschema` verifies.

**Comment by manycoding** [comment]
`%memit` for `Arche.report_all()` with schema, 10_000 items:
* np, list, df (where I am moving to)
peak memory: 223.23 MiB, increment: 29.59 MiB

* df (current broken way)
peak memory: 197.89 MiB, increment: 69.20 MiB

* df, dict (the old way)
peak memory: 383.12 MiB, increment: 26.45 MiB
