### ISSUE TITLE
data_quality_report() fails if executed before report_all()

### ISSUE THREAD

**Issue by Alexandr1988** [scrapinghub/arche#95]
DQR responds with this error: `validate() got an unexpected keyword argument 'df'`
https://github.com/scrapinghub/arche/commit/9fd17df193917773e0f72cc0ca001a5506febf9e#r33664865 - possible place to start checking the reason of the issue

**Comment by manycoding** [comment]
Thanks, this pr is not the reason.
When I changed raw data format to numpy array from df in this one https://github.com/scrapinghub/arche/commit/459dfacb4864ff1431af708a122700fd26a145c9 I forgot to update DQR.
First, I need to write a test.

**Comment by manycoding** [comment]
Closed by #96
